services:
  app:
    # build:
    #   context: .
    #   dockerfile: docker/php/Dockerfile
    image: devojannewbie/laravel-11-breeze-starter:1.0
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      # - ./apps/laravel-breeze-starter:/var/www
      - app_data:/var/www
      - ./docker/file-uploads-breeze:/var/www/storage/app/public/uploads
    depends_on:
      - db
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8800:80"
    volumes:
      # - ./apps/laravel-breeze-starter:/var/www
      - app_data:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3312:3306"
    volumes:
      - ./docker/mysql-breeze:/var/lib/mysql
    healthcheck: # ✅ Tambahan untuk cek siapnya DB
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app_data:
    external: false
