services:
  app:
    build:
      image: devojannewbie/laravel-online-store-starter:latest
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./app/online-store-laravel-11:/var/www
    depends_on:
      - db
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - ./app/online-store-laravel-11:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
